# application: emgeosci
# version: 1
runtime: python37
api_version: 1
threadsafe: yes


handlers:

# favicon
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always

# all css
- url: /(.*\.css)
  mime_type: text/css
  static_files: _build/html/\1
  upload: _build/html/(.*\.css)
  secure: always

# webfonts
- url: /(.*\.(eot|svg|ttf|woff|woff2|otf))
  static_files: _build/html/\1
  upload: _build/html/(.*\.(eot|svg|ttf|woff|woff2|otf))
  secure: always

# javascript
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: _build/html/\1
  upload: _build/html/(.*\.js)
  secure: always

# plain text source
- url: /(.*\.txt)
  mime_type: text/plain
  static_files: _build/html/\1
  upload: _build/html/(.*\.txt)
  secure: always

  # python source files
- url: /(.*\.py)
  static_files: _build/html/\1
  upload: _build/html/(.*\.py)
  secure: always

# images
- url: /_images/(.*\.(gif|png|jpg|ico))
  static_files: _build/html/_images/\1
  upload: _build/html/_images/(.*\.(gif|png|jpg|ico))
  secure: always

# plot directive images
- url: /(.*\.(gif|png|jpg|ico|pdf))
  static_files: _build/html/\1
  upload: _build/html/(.*\.(gif|png|jpg|ico|pdf))
  secure: always

# redirect en/latest traffic
- url: /en/latest/(.*\.html)
  script: emgeosci.app
  secure: always

# raw html
- url: /(.*\.html)
  mime_type: text/html
  static_files: _build/html/\1
  upload: _build/html/(.*\.html)
  secure: always

- url: /error.html
  static_files: _templates/error.html
  upload: _templates/error.html
  secure: always


# serve index files
- url: /(.+)/
  script: emgeosci.app
  secure: always
  # static_files: _build/html/\1/index.html
  # upload: _build/html/(.+)/index.html

- url: /(.+)
  script: emgeosci.app
  secure: always
  # static_files: _build/html/\1/index.html
  # upload: _build/html/(.+)/index.html

# - url: /
#   static_files: _build/html/index.html
#   upload: _build/html/index.html

# - url: /.*
#   static_files: _templates/error.html
#   upload: _templates/error.html

- url: .*
  script: emgeosci.app
  secure: always

# Recommended file skipping declaration from the GAE tutorials
skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^(.*/)?.*\.doctree$
  - ^(.*/)?doctrees/.*
  - miniconda.sh

libraries:
- name: webapp2
  version: "2.5.2"
- name: PIL
  version: "1.1.7"
- name: numpy
  version: "latest"
- name: jinja2
  version: "latest"
- name: ssl
  version: "latest"

