# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: EM Website Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        # Gather requirements and install older version of geoana
        cat requirements.txt | grep -v "^geoana" > requirements-ci.txt
        cat requirements-build-geoana.txt | grep -v "^#" >> requirements-ci.txt
        pip install -r requirements-ci.txt
        rm requirements-ci.txt
        pip install --no-build-isolation geoana==0.1.3

        # Install extra packages
        pip install flake8 pytest
    - name: Test with pytest
      run: |
        pytest -s -v tests

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        # Gather requirements and install older version of geoana
        cat requirements.txt | grep -v "^geoana" > requirements-ci.txt
        cat requirements-build-geoana.txt | grep -v "^#" >> requirements-ci.txt
        pip install -r requirements-ci.txt
        rm requirements-ci.txt
        pip install --no-build-isolation geoana==0.1.3

    - name: Build pages
      run: |
        python _ext/build_contrib_case.py
        make html
        python _ext/copy_images.py

    - name: GitHub Pages
      # Only deploy if the event that triggered was a push to main
      # (only pushes to main triggers builds, see 'on' condition in the
      # beginning of the file)
      if: success() && github.event_name == 'push'
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        build_dir: _build/html
        fqdn: em.geosci.xyz
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
